version: 2

models:
    - name: raw_calls
      description: "Raw data transformed from source"
    - name: fact_calls
      description: "A fact table transformed by dbt"
      columns:
          - name: guid
            description: "The call guid"
            tests:
                - not_null
                - unique
          - name: start_timestamp
            description: "Timestamp of call start"
            tests:
                - not_null
          - name: agent_id
            description: "Participating agent id"
            tests:
                - not_null
          - name: total_duration
            description: "The total duration of call"
            tests: 
                - duration_stages_sum
                - not_null
          - name: "'endReason'"
            description: "The reason for ending the call"
            tests:
                - not_null
          - name: ringing_duration
            description: "The duration of ringing"
          - name: connected_duration
            description: "The duration of connecting"
          - name: wrap_duration
            description: "The duration of Wrapping"  
    